language: android
jdk: oraclejdk8
env:
  matrix:
  - ANDROID_TARGET=android-24  ANDROID_ABI=armeabi-v7a
android:
  components:
  - tools
  - android-24
  - build-tools-24.0.1
  - platform-tools
before_install:
- export ANDROID_HOME=/usr/local/android-sdk
- export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
- echo "sdk.dir=$ANDROID_HOME" > local.properties
script:
- cd SampleApp/
- ./gradlew clean assembleDebug
notifications:
  webhooks:
    urls:
    - secure: ZbnbVXnG+HrsBmYz0kyXk3XogdZ7IU/FhUMKi8ZKa7r+9xKDIpnxwZH2yO+dRffjIGQGzuPChgMtRexwOASp7YwqEkHI8n5donKCzKEJraLA5C9O1bgpam3U8g8wZl8bUY3u+SnYxB2aN1ZIgBxwcDJAlgpC/YM7kDEBDhEQaTY=
    on_success: change
    on_failure: always
