package io.card.payment.i18n.locales;

import java.util.ArrayList;
import java.util.List;

import io.card.payment.i18n.StringKey;
import io.card.payment.i18n.SupportedLocale;

// Class autogenerated!  Do not modify.
// Generated on 2014-12-10 11:29:25.185885 via script:
// /Users/twhipple/Documents/buffalo/lib-i18n/i18n/script/generate_android_i18n.py -java_src_path src/ -java_gen_path gen/ -stringkey_path io/card/payment/i18n/ -strings_path ../strings/projects/card.io/strings/ --strict

public class LocalizedStringsList {
    public static final List<SupportedLocale<StringKey>> ALL_LOCALES = new ArrayList<SupportedLocale<StringKey>>();

    static {
        ALL_LOCALES.add(new LocalizedStringsAR());
        ALL_LOCALES.add(new LocalizedStringsDA());
        ALL_LOCALES.add(new LocalizedStringsDE());
        ALL_LOCALES.add(new LocalizedStringsEN());
        ALL_LOCALES.add(new LocalizedStringsEN_AU());
        ALL_LOCALES.add(new LocalizedStringsEN_GB());
        ALL_LOCALES.add(new LocalizedStringsES());
        ALL_LOCALES.add(new LocalizedStringsES_MX());
        ALL_LOCALES.add(new LocalizedStringsFR());
        ALL_LOCALES.add(new LocalizedStringsHE());
        ALL_LOCALES.add(new LocalizedStringsIS());
        ALL_LOCALES.add(new LocalizedStringsIT());
        ALL_LOCALES.add(new LocalizedStringsJA());
        ALL_LOCALES.add(new LocalizedStringsKO());
        ALL_LOCALES.add(new LocalizedStringsMS());
        ALL_LOCALES.add(new LocalizedStringsNB());
        ALL_LOCALES.add(new LocalizedStringsNL());
        ALL_LOCALES.add(new LocalizedStringsPL());
        ALL_LOCALES.add(new LocalizedStringsPT());
        ALL_LOCALES.add(new LocalizedStringsPT_BR());
        ALL_LOCALES.add(new LocalizedStringsRU());
        ALL_LOCALES.add(new LocalizedStringsSV());
        ALL_LOCALES.add(new LocalizedStringsTH());
        ALL_LOCALES.add(new LocalizedStringsTR());
        ALL_LOCALES.add(new LocalizedStringsZH_HANS());
        ALL_LOCALES.add(new LocalizedStringsZH_HANT());
        ALL_LOCALES.add(new LocalizedStringsZH_HANT_TW());
    }
}
