package com.paypal.android.i18n.locales;

import java.util.HashMap;
import java.util.Map;
import com.paypal.android.i18n.SupportedLocale;
import io.card.payment.i18n.StringKey;

// Class autogenerated!  Do not modify.
// Generated on 2014-12-10 11:29:25.135807 via script:
// /Users/twhipple/Documents/buffalo/lib-i18n/i18n/script/generate_android_i18n.py -java_src_path src/ -java_gen_path gen/ -stringkey_path io/card/payment/i18n/ -strings_path ../strings/projects/card.io/strings/ --strict

public class LocalizedStringsEN_SE implements SupportedLocale<StringKey> {

    private static Map<StringKey, String> mDisplay = new HashMap<StringKey, String>();
    private static Map<String, String> mAdapted = new HashMap<String, String>();
    private static Map<String, String> mErrors = new HashMap<String, String>();

    @Override
    public String getName() {
        return "en_SE";
    }

    @Override
    public String getAdaptedDisplay(StringKey key, String country) {
        String adaptedKey = key.toString() + "|" + country;
        if (mAdapted.containsKey(adaptedKey)) {
            return mAdapted.get(adaptedKey);
        } else {
            return mDisplay.get(key);
        }
    }

    @Override
    public String getError(String key) {
        return mErrors.get(key);
    }

    public LocalizedStringsEN_SE(){
        mDisplay.put(StringKey.CANCEL, "Cuncel");
        mDisplay.put(StringKey.CARDTYPE_AMERICANEXPRESS, "Emereecun Ixpress");
        mDisplay.put(StringKey.CARDTYPE_DISCOVER, "Deescufer");
        mDisplay.put(StringKey.CARDTYPE_JCB, "JCB");
        mDisplay.put(StringKey.CARDTYPE_MASTERCARD, "MesterCerd");
        mDisplay.put(StringKey.CARDTYPE_VISA, "Feesa");
        mDisplay.put(StringKey.DONE, "Börk Börk Börk!");
        mDisplay.put(StringKey.ENTRY_CVV, "CFF");
        mDisplay.put(StringKey.ENTRY_POSTAL_CODE, "Pustel Cude");
        mDisplay.put(StringKey.ENTRY_EXPIRES, "Expures");
        mDisplay.put(StringKey.EXPIRES_PLACEHOLDER, "MM/YY");
        mDisplay.put(StringKey.SCAN_GUIDE, "Huld cerd here-a.\nIt veell scun ootumeteecelly.");
        mDisplay.put(StringKey.KEYBOARD, "Keybuerd…");
        mDisplay.put(StringKey.ENTRY_CARD_NUMBER, "Cerd Noomber");
        mDisplay.put(StringKey.MANUAL_ENTRY_TITLE, "Cerd Deteeels");
        mDisplay.put(StringKey.ERROR_NO_DEVICE_SUPPORT, "Thees defeece-a cunnut use-a zee cemera tu reed cerd noombers.");
        mDisplay.put(StringKey.ERROR_CAMERA_CONNECT_FAIL, "Device camera is unavailable.");
        mDisplay.put(StringKey.ERROR_CAMERA_UNEXPECTED_FAIL, "Zee defeece-a hed un unexpected irrur oopeneeng zee cemera.");

        // no adapted_translations found
        // no error_translations found
    }
}
